FROM busybox

RUN mkdir -p /tmp/learningBase/train /tmp/learningBase/validation

COPY training_data.csv /tmp/learningBase/train/
COPY testing_data.csv /tmp/learningBase/validation/
COPY ReadMe.md /tmp/learningBase/

CMD ["echo", "learningBase Image is ready!"]
