FROM ubuntu:latest

RUN mkdir -p /tmp/codeBase
WORKDIR /tmp/codeBase
RUN apt-get update  && apt-get install python3 -y && apt-get install python3-pandas -y && apt-get install git -y && git clone https://github.com/MarcusGrum/pybrain.git
RUN apt-get install python3-statsmodels python3-numpy python3-pil python3-matplotlib python3-seaborn python3-sklearn -y

COPY activation_ai.py /tmp/codeBase/
COPY activation_ols.py /tmp/codeBase/
COPY activation_data.csv /tmp/codeBase/
COPY ReadMe.md /tmp/codeBase/

CMD ["echo", "codeBase Image is ready!"]
