FROM python:3

RUN mkdir -p /tmp/codeBase
WORKDIR /tmp/codeBase
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/MarcusGrum/pybrain.git

COPY activation_ai.py /tmp/codeBase/
COPY activation_ols.py /tmp/codeBase/
COPY activation_data.csv /tmp/codeBase/
COPY ReadMe.md /tmp/codeBase/

CMD ["echo", "codeBase Image is ready!"]
