# Dockerfile activationBase
FROM busybox:latest

# Create directory
RUN mkdir -p /tmp/activationBase

# Add the activation Data in the following path
ADD ../../data/activation_data.csv /tmp/activationBase/

# Add README 
COPY README.activationBase.md /tmp/activationBase/



