# Image busybox
FROM busybox:latest

# Copies the AI/OLS model and the ReadMe file
COPY currentAiSolution.xml /tmp/knowledgeBase/
COPY currentOlsSolution.xml /tmp/knowledgeBase/
COPY ReadMe.md /tmp/knowledgeBase/

# Output after creating the Image
CMD ["echo", "knowledgeBase Image is ready!"]