# Image busybox
FROM busybox

# Copies the AI/OLS model and the ReadMe file
COPY currentAiSolution.xml /tmp/knowledgeBase/currentAiSolution.xml
COPY currentPklSolution.pkl /tmp/knowledgeBase/currentOlsSolution.xpkl
ADD ReadMe.md /tmp/knowledgeBase/

# Output after creating the Image
CMD ["echo", "knowledgeBase Image is ready!"]
