# Image busybox
FROM busybox

# Copies the AI/OLS model and the ReadMe file
ADD currentAiSolution.xml /knowledgeBase/currentAiSolution.xml
ADD currentOlsSolution.xml /knowledgeBase/currentOlsSolution.xml
ADD ReadMe.md /tmp/knowledgeBase/

# Output after creating the Image
CMD ["echo", "knowledgeBase Image is ready!"]