version: "3.8"
services:
    knowledgeBase:
        image: schummel/knowledgebase_aibas_kurs_ps_ms:latest
        volumes:
        -   type: bind
            source: ./ai_system
            target: /tmp/ai_system
        command:
                cp -r /tmp/knowledgeBase /tmp/ai_system/

    activationBase:
        image: schummel/activationbase_aibas_kurs_ps_ms:latest
        volumes:
        -   type: bind
            source: ./ai_system
            target: /tmp/ai_system
        command:      
                cp -r /tmp/activationBase /tmp/ai_system/
    codeBase:
        image: schummel/codebase_aibas_kurs_ps_ms:latest
        volumes:
        -   type: bind
            source: ./ai_system
            target: /tmp/ai_system
        command: 
            cp -r /tmp/codeBase /tmp/ai_system/ ;
                python3 /tmp/codeBase/model.py 
volumes:
  ai_system: